name: Build and Deploy to GitHub Pages
on:
  schedule:
    # Runs at 12:00 AM CT (6:00 AM UTC, adjust for daylight saving)
    - cron: '0 6 * * *' # 12 AM CT = 6 AM UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4

      - name: Build your site
        run: |
          # Your build commands here
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out # Updated to your output directory
